# Generated by Django 4.1.7 on 2023-02-21 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='user/profile/default.jpeg', upload_to='user/profile/avatar'),
        ),
    ]
