# Generated by Django 4.1.7 on 2023-02-21 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='converted_into_clients',
            field=models.BooleanField(default=False),
        ),
    ]
